### PR TITLE
* Change gem to depend on factory_bot instead of deprecated factory_girl

### LINKED ISSUE #21: Change dependency to factory_bot?
It is renamed recently
https://github.com/thoughtbot/factory_bot

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fix #21

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Anything else needed?

**Comment by divineforest** [comment]
@Neodelf pls, accept

**Comment by PikachuEXE** [comment]
Some review would be great...

**Comment by PikachuEXE** [comment]
@Neodelf
Please take a look when free thanks

**Comment by PikachuEXE** [comment]
Anything else needed?

**Comment by PikachuEXE** [comment]
@Neodelf Please comment or merge :S

**Comment by PikachuEXE** [comment]
Waiting for merge...

**Comment by Fernan2** [comment]
👏

**Comment by divineforest** [comment]
@PikachuEXE done

**Comment by PikachuEXE** [comment]
Will release soon? (last release is in 2014 wow)

**Comment by divineforest** [comment]
@PikachuEXE @Fernan2 released https://rubygems.org/gems/factory_girl-seeds

**Comment by Neodelf** [comment]
Guys, I have figured out that I missed mentions. Sorry about that

**Pull request merged**
